# 
FROM python:3.9-slim

# This is directory inside container
WORKDIR /cont_transmiim

# Copy requirements file
COPY ./requirements.txt /cont_transmiim/requirements.txt

# 
RUN pip3 install --no-cache-dir --upgrade -r /cont_transmiim/requirements.txt

# Copy remaining parts of code to container
COPY ./src /cont_transmiim/src

# Expose this specific port to web traffic
EXPOSE 8501

# Telling docker on how to test if a container is still working
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT [ "streamlit", "run", "src/main.py", "--server.port=8501", "--server.address=0.0.0.0" ]